### ISSUE TITLE
Npm install 出现错误

### ISSUE THREAD

**Issue by huanghuzi639** [sohaha/naiveui-admin-template#2]
D:\vuecs\naiveui-admin-template>npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: zls-template@0.0.1
npm error Found: vite@4.5.5
npm error node_modules/vite
npm error   dev vite@"^4.4.9" from the root project
npm error
npm error Could not resolve dependency:
npm error peer vite@"^2.9.0 || ^3.0.0" from vite-plugin-restart@0.2.0
npm error node_modules/vite-plugin-restart
npm error   dev vite-plugin-restart@"^0.2.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\jun\AppData\Local\npm-cache\_logs\2024-10-25T02_49_04_479Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\jun\AppData\Local\npm-cache\_logs\2024-10-25T02_49_04_479Z-debug-0.log

**Comment by sohaha** [comment]
因为个人使用的是 `PNPM`, 你试试:

```bash
npm i -g pnpm
pnpm i
```
